services:
  - type: web
    name: multilang_site
    env:
      - key: DJANGO_SETTINGS_MODULE
        value: "multilang_site.settings"
    build:
      - steps:
          - name: Install dependencies
            env: python=python3.8
            script:
              - pip install -r requirements.txt
          - name: Collect static files
            script:
              - python manage.py collectstatic --noinput
          - name: Migrate database
            script:
              - python manage.py migrate
          - name: Start server
            script:
              - gunicorn multilang_site.wsgi --workers 4 --bind 0.0.0.0:8000
    port: 8000
